dist: xenial
sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy2.7-6.0
  - pypy3.5

install:
  - pip install .[tests]
  - pip install gunicorn psycopg2 mysql-connector-python
script:
  - ./misc/travis_test.sh
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
services:
  - mysql
  - postgresql
notifications:
  email: false
